- Macro Average
- Weighted Average
- Micro Average

In [1]:
# 기본 작업 경로 설정
import os
notebook_path = os.path.abspath("../readme.md")
notebook_dir = os.path.dirname(notebook_path)
os.chdir(notebook_dir)

# 현재 작업 디렉토리 출력
print("Current working directory: ", os.getcwd())

Current working directory:  /mnt/e/py_data/project_3_git


# yolo check

In [4]:
import pandas as pd

# 데이터 불러오기
data = pd.read_csv("models/yolov10/runs/detect/train/results.csv")

# metrics/mAP50-95(B) 의 최대 값 row
max_row = data[data["    metrics/mAP50-95(B)"] == data["    metrics/mAP50-95(B)"].max()]

In [5]:
todict_best = max_row.to_dict()
todict_bset_clean = {}  
for i in todict_best:
    i_ = i.strip(' ')
    todict_bset_clean[i_] = (todict_best[i][52])

In [6]:
todict_bset_clean['metrics/mAP50(B)']

0.89814

In [41]:
from ultralytics import YOLOv10

# 모델 로드
model = YOLOv10("models/yolov10n-face.pt")  # 모델 가중치 파일 경로

# 평가 데이터셋 경로
data_config = "data/yolo_data/wassup_data.yaml"  # 데이터셋 구성 파일 경로

# 모델 평가
results = model.val(data=data_config)

/home/tommy/miniconda3/envs/p3/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/tommy/miniconda3/envs/p3/lib/python3.11/site-packages/ultralytics/nn/tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.

Ultralytics YOLOv8.1.34 🚀 Python-3.11.9 torch-2.4.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12287MiB)
YOLOv10n summary (fused): 285 layers, 2695976 parameters, 0 gradients, 8.2 GFLOPs


val: Scanning /mnt/e/py_data/project_3_git/data/yolo_data/val.cache... 1199 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1199/1199 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 75/75 [01:06<00:00,  1.12it/s]


                   all       1199       1199      0.862        0.8      0.897      0.782
                 anger       1199        300      0.813      0.709      0.854      0.748
                   sad       1199        300      0.877      0.797      0.907      0.786
                 panic       1199        300      0.808       0.76      0.853      0.741
                 happy       1199        299      0.949      0.936      0.975      0.852
Speed: 0.3ms preprocess, 5.2ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /mnt/e/py_data/project_3_git/yolov10/runs/detect/val


In [42]:
results

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7fb86d1ec050>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0

# detectron check

In [8]:
import json

with open("models/faster_rcnn_R_50_FPN_3x/metrics.json", "r") as f:
    data = json.load(f)

In [9]:
best = 0
for i in best:
    if 'bbox/AP' in i.keys():
        if i['bbox/AP'] > best:
            best = i['bbox/AP']
            best_all = i

In [10]:
best

74.22026454929797

In [11]:
best_all

{'bbox/AP': 74.22026454929797,
 'bbox/AP-angry': 71.10706908585664,
 'bbox/AP-happy': 82.1146599904562,
 'bbox/AP-sad': 72.93612316406849,
 'bbox/AP-surprised': 70.7232059568105,
 'bbox/AP50': 87.23360060189019,
 'bbox/AP75': 86.68936575410613,
 'bbox/APl': 74.22026454929797,
 'bbox/APm': 0,
 'bbox/APs': 0,
 'data_time': 1.5770274579990655,
 'eta_seconds': 1503805.9204250786,
 'fast_rcnn/cls_accuracy': 0.976806640625,
 'fast_rcnn/false_negative': 0.010337642910567369,
 'fast_rcnn/fg_cls_accuracy': 0.9106901003759351,
 'iteration': 6999,
 'loss_box_reg': 0.11586455628275871,
 'loss_cls': 0.05802210234105587,
 'loss_rpn_cls': 4.542133683571592e-05,
 'loss_rpn_loc': 0.0014480188256129622,
 'lr': 0.000999664388727941,
 'rank_data_time': 1.5770274579990655,
 'roi_head/num_bg_samples': 103.09375,
 'roi_head/num_fg_samples': 24.90625,
 'rpn/num_neg_anchors': 252.15625,
 'rpn/num_pos_anchors': 3.84375,
 'time': 2.5226071160032006,
 'total_loss': 0.17473797223465226}

In [12]:
best_all['bbox/AP50']

87.23360060189019

In [5]:
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.structures import Boxes, Instances
from detectron2.data.datasets import register_coco_instances
from detectron2.data import build_detection_test_loader

from loguru import logger
import numpy as np
import json
import cv2
import sys

# 설정을 로드
cfg = get_cfg()
cfg.merge_from_file("detectron2/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.WEIGHTS = ("models/faster_rcnn_R_50_FPN_3x//model_0006999.pth")  # 훈련된 모델의 가중치 파일 경로
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # 예측에 사용할 임계값
cfg.DATASETS.TEST = ("face_data_set_valid", )  # 테스트 데이터셋 이름
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4

# 예측기를 설정
predictor = DefaultPredictor(cfg)

# 예측할 이미지를 로드
image_path = "test.png"  # 예측에 사용할 이미지 경로
image = cv2.imread(image_path)

# 예측을 수행
outputs = predictor(image)

# 예측 결과를 확인
print(outputs)

/home/tommy/miniconda3/envs/p3/lib/python3.11/site-packages/fvcore/common/checkpoint.py:252: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(f, map_location=

{'instances': Instances(num_instances=1, image_height=700, image_width=1400, fields=[pred_boxes: Boxes(tensor([[ 754.8625,  122.4452, 1005.7634,  435.7304]], device='cuda:0')), scores: tensor([0.9488], device='cuda:0'), pred_classes: tensor([2], device='cuda:0')])}


In [40]:
from detectron2.data.datasets import register_coco_instances
from detectron2.data import build_detection_test_loader
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from loguru import logger


# 이전 로그 삭제
logger.remove()
# 로그 경로 설정
logger.add(f"logs/eval_validateion_of_rcnn.log",format="{message}", level="INFO")
# 데이터셋 등록
register_coco_instances("face_data_set_valid", {}, "data/ssd_rcnn_face/annotations_val.json", "data/yolo_data/val/")

# 설정을 로드
cfg = get_cfg()
cfg.merge_from_file("detectron2/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TEST = ("face_data_set_valid", )  # 테스트 데이터셋 이름

# 훈련시 사용한 임계값 설정
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = ("models/faster_rcnn_R_50_FPN_3x/model_0006999.pth")  # 훈련된 모델의 가중치 파일 경로
cfg.INPUT.MIN_SIZE_TEST = 512
cfg.INPUT.MAX_SIZE_TEST = 512
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4
cfg.TEST.EVAL_PERIOD = 1000




# 평가자 생성
evaluator = COCOEvaluator("face_data_set_valid", cfg, False, output_dir=f"models/faster_rcnn_R_50_FPN_3x/metrics_out/metrics_valid.json")

predictor = DefaultPredictor(cfg)
# 테스트 데이터 로더 생성
val_loader = build_detection_test_loader(cfg, "face_data_set_valid")

# 평가 수행
results = inference_on_dataset(predictor.model, val_loader, evaluator)

# 결과 출력
logger.info(f"Results: {results}")


COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.


/home/tommy/miniconda3/envs/p3/lib/python3.11/site-packages/fvcore/common/checkpoint.py:252: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(f, map_location=

Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.742
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.872
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.867
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.742
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.859
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.860
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.860
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.5

# 결과

```py
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.742
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.872
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.867
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.742
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.859
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.860
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.860
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.860
```